app:
  baseUrl: https://devportal.197.140.32.144.sslip.io
  extensions:
  - page:catalog:
      config:
        path: /
  - entity-content:kubernetes/kubernetes
  - entity-content:argocd/argocd
  title: DevPortal

auth:
  environment: development
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
    oidc:
      development:
        callbackUrl: https://197.140.32.65:30443/api/auth/oidc/handler/frame
        clientId: backstage
        clientSecret: YbwffCiztqtx3AuRQbZfMPFJalg3SmTC
        metadataUrl: https://197.140.32.151:30900/realms/DevPortal/.well-known/openid-configuration
        prompt: auto
        signIn:
          resolvers:
            - resolver: emailLocalPartMatchingUserEntityName

session:
  secret: my-backstage-session-secret

backend:
  baseUrl: https://devportal.197.140.32.144.sslip.io
  cors:
    credentials: true
    methods:
      - GET
      - HEAD
      - PATCH
      - POST
      - PUT
      - DELETE
    origin: https://devportal.197.140.32.144.sslip.io
  csp:
    connect-src:
      - "'self'"
      - 'http:'
      - 'https:'
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      password: ${POSTGRES_PASSWORD}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
  listen:
    port: 7007

catalog:
  rules:
  - allow:
    - Component
    - System
    - API
    - Resource
    - Location
    - User
    - Group
    - Template
  locations:
    - type: url
      target: https://github.com/devportal-labs/idp-openstack/blob/main/org.yaml
      rules:
        - allow: [Group, System, User]
  providers:
    github:
      devportalLabs:
        catalogPath: /catalog-info.yaml
        filters:
          branch: main
          repository: .*
        organization: Abderraoufzekkour
        schedule:
          frequency:
            minutes: 5
          timeout:
            minutes: 3
    githubOrg:
      githubUrl: https://github.com/Abderraoufzekkour
      id: devportalLabsOrg
      schedule:
        frequency:
          minutes: 10
        timeout:
          minutes: 3
    keycloakOrg:
      default:
        baseUrl: https://197.140.32.151:30900
        loginRealm: DevPortal
        realm: DevPortal
        clientId: backstage
        clientSecret: YbwffCiztqtx3AuRQbZfMPFJalg3SmTC
        schedule:
          frequency: { minutes: 1 }
          timeout: { minutes: 3 }

integrations:
  github:
  - host: github.com
    token: ${GITHUB_TOKEN}

notifications:
  enabled: false

organization:
  name: DevPortal

permission:
  enabled: false

kubernetes:
  serviceLocatorMethod:
    type: multiTenant
  clusterLocatorMethods:
    - type: config
      clusters:
        - url: https://10.96.0.1
          name: local-cluster
          authProvider: serviceAccount
          skipTLSVerify: true
          skipMetricsLookup: true

argocd:
  appLocatorMethods:
    - type: config
      instances:
        - name: argoInstance1
          url: https://197.140.32.65:30808
          username: ${ARGOCD_USERNAME}
          password: ${ARGOCD_PASSWORD}

proxy:
  '/argocd/api':
    target: https://197.140.32.65:30808/api/v1/
    changeOrigin: true
    secure: false
    headers:
      Authorization: Bearer ${ARGOCD_AUTH_TOKEN}
