app:
  title: DevPortal
  baseUrl: https://197.140.32.65:30443

backend:
  baseUrl: https://197.140.32.65:30443
  listen:
    port: 7007
  csp:
    connect-src: ["self", 'http:', 'https:']
  cors:
    origin: https://197.140.32.65:30443
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

auth:
  environment: development
  session:
    secret: my-backstage-session-secret
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
    oidc:
      development:
        metadataUrl: https://197.140.32.151:30900/realms/devportal/.well-known/openid-configuration
        clientId: backstage
        clientSecret: YbwffCiztqtx3AuRQbZfMPFJalg3SmTC
        prompt: auto
        callbackUrl: https://197.140.32.65:30443/api/auth/oidc/handler/frame
        signIn:
          resolvers:
            - resolver: emailLocalPartMatchingUserEntityName

catalog:
  providers:
    github:
      providerId:
        organization: devportal-labs
        catalogPath: /catalog-info.yaml
        filters:
          branch: main
        schedule:
          frequency: { minutes: 1 }
          timeout: { minutes: 3 }
