app:
  title: DevPortal
  baseUrl: https://devportal.197.140.32.144.sslip.io:30443
  packages: all
  extensions:
    - page:catalog:
        config:
          path: /

organization:
  name: DevPortal

backend:
  baseUrl: https://devportal.197.140.32.144.sslip.io:30443
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: https://devportal.197.140.32.144.sslip.io:30443
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
  actions:
    pluginSources:
      - auth
      - catalog
      - scaffolder

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

proxy: {}

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'

auth:
  environment: development
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true

scaffolder: {}

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, User, Group, Template]
  locations:
    - type: url
      target: https://github.com/Abderraoufzekkour/idp-openstack/blob/main/backstage/catalog/all.yaml
      rules:
        - allow: [Component, System, API, Resource, Location, User, Group, Template]

kubernetes:
  serviceLocatorMethod:
    type: multiTenant
  clusterLocatorMethods:
    - type: config
      clusters:
        - name: devportal-cluster
          url: https://197.140.32.144:6443
          authProvider: serviceAccount
          skipTLSVerify: true
          serviceAccountToken: ${K8S_SA_TOKEN}

permission:
  enabled: false
