apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: idp-openstack
  title: IDP OpenStack
  description: OpenStack Infrastructure for IDP
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: production
  owner: user:default/guest
