apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: idp-openstack
  title: IDP OpenStack
  description: OpenStack Infrastructure for IDP
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/source-location: url:https://github.com/Abderraoufzekkour/idp-openstack/tree/main/
spec:
  type: service
  lifecycle: production
  owner: user:default/guest
