site_name: 'PlatformOne IDP'
site_description: 'Enterprise Internal Developer Platform Documentation'
plugins:
  - techdocs-core
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Deployment: deployment.md
