apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xopenstackinstances.compute.idp.io
spec:
  compositeTypeRef:
    apiVersion: compute.idp.io/v1alpha1
    kind: XOpenStackInstance
  providerConfigRef:
    name: openstack-provider
  resources:
    - name: openstack-vm
      base:
        apiVersion: compute.openstack.crossplane.io/v1alpha1
        kind: Instance
        spec:
          forProvider:
            flavorName: m1.small
            imageName: ubuntu-22.04
            networks:
              - name: public
            securityGroups:
              - name: default
      patches:
        - fromFieldPath: "spec.parameters.instanceName"
          toFieldPath: "metadata.name"
        - fromFieldPath: "spec.parameters.flavorName"
          toFieldPath: "spec.forProvider.flavorName"
